package com.babulens.weighbridge.repository;

import com.babulens.weighbridge.model.entity.Invoice;
import org.springframework.data.repository.CrudRepository;
import org.springframework.stereotype.Repository;

import java.util.Date;
import java.util.List;

@Repository
public interface InvoiceDAO extends CrudRepository<Invoice, String> {

	Invoice findFirstByDummyAndInvoiceNoAndProfileOrderByInvoiceNoDesc(boolean dummy, int invoiceNo, String profile);

	List<Invoice> findAllByInvoiceNoGreaterThanEqualAndInvoiceTimeGreaterThanEqualAndInvoiceTimeLessThanEqualAndProfileOrderByInvoiceNoAsc(int invoiceNo, Date startInvoiceTime, Date endInvoiceTime, String profile);

	List<Invoice> findAllByReferenceSlipNoGreaterThanEqualAndInvoiceTimeGreaterThanEqualAndInvoiceTimeLessThanEqualAndProfileOrderByInvoiceNoAsc(int referenceSlipNo, Date startInvoiceTime, Date endInvoiceTime, String profile);

	List<Invoice> findAllByCustomersNameContainingAndInvoiceTimeGreaterThanEqualAndInvoiceTimeLessThanEqualAndProfileOrderByInvoiceNoAsc(String customersName, Date startInvoiceTime, Date endInvoiceTime, String profile);

	List<Invoice> findAllByVehicleNoContainingAndInvoiceTimeGreaterThanEqualAndInvoiceTimeLessThanEqualAndProfileOrderByInvoiceNoAsc(String vehicleNo, Date startInvoiceTime, Date endInvoiceTime, String profile);

	List<Invoice> findAllByMaterialContainingAndInvoiceTimeGreaterThanEqualAndInvoiceTimeLessThanEqualAndProfileOrderByInvoiceNoAsc(String material, Date startInvoiceTime, Date endInvoiceTime, String profile);

	List<Invoice> findAllByInvoiceTimeGreaterThanEqualAndInvoiceTimeLessThanEqualAndProfileOrderByInvoiceNoAsc(Date startInvoiceTime, Date endInvoiceTime, String profile);

	List<Invoice> findAllByInvoiceNoGreaterThanEqualAndInvoiceTimeGreaterThanEqualAndInvoiceTimeLessThanEqualAndDummyTrueAndProfileOrderByInvoiceNoAsc(int invoiceNo, Date startInvoiceTime, Date endInvoiceTime, String profile);

	List<Invoice> findAllByReferenceSlipNoGreaterThanEqualAndInvoiceTimeGreaterThanEqualAndInvoiceTimeLessThanEqualAndDummyTrueAndProfileOrderByInvoiceNoAsc(int referenceSlipNo, Date startInvoiceTime, Date endInvoiceTime, String profile);

	List<Invoice> findAllByCustomersNameContainingAndInvoiceTimeGreaterThanEqualAndInvoiceTimeLessThanEqualAndDummyTrueAndProfileOrderByInvoiceNoAsc(String customersName, Date startInvoiceTime, Date endInvoiceTime, String profile);

	List<Invoice> findAllByVehicleNoContainingAndInvoiceTimeGreaterThanEqualAndInvoiceTimeLessThanEqualAndDummyTrueAndProfileOrderByInvoiceNoAsc(String vehicleNo, Date startInvoiceTime, Date endInvoiceTime, String profile);

	List<Invoice> findAllByMaterialContainingAndInvoiceTimeGreaterThanEqualAndInvoiceTimeLessThanEqualAndDummyTrueAndProfileOrderByInvoiceNoAsc(String material, Date startInvoiceTime, Date endInvoiceTime, String profile);

	List<Invoice> findAllByInvoiceTimeGreaterThanEqualAndInvoiceTimeLessThanEqualAndDummyTrueAndProfileOrderByInvoiceNoAsc(Date startInvoiceTime, Date endInvoiceTime, String profile);

	List<Invoice> findAllByInvoiceNoGreaterThanEqualAndInvoiceTimeGreaterThanEqualAndInvoiceTimeLessThanEqualAndDummyFalseAndProfileOrderByInvoiceNoAsc(int invoiceNo, Date startInvoiceTime, Date endInvoiceTime, String profile);

	List<Invoice> findAllByReferenceSlipNoGreaterThanEqualAndInvoiceTimeGreaterThanEqualAndInvoiceTimeLessThanEqualAndDummyFalseAndProfileOrderByInvoiceNoAsc(int referenceSlipNo, Date startInvoiceTime, Date endInvoiceTime, String profile);

	List<Invoice> findAllByCustomersNameContainingAndInvoiceTimeGreaterThanEqualAndInvoiceTimeLessThanEqualAndDummyFalseAndProfileOrderByInvoiceNoAsc(String customersName, Date startInvoiceTime, Date endInvoiceTime, String profile);

	List<Invoice> findAllByVehicleNoContainingAndInvoiceTimeGreaterThanEqualAndInvoiceTimeLessThanEqualAndDummyFalseAndProfileOrderByInvoiceNoAsc(String vehicleNo, Date startInvoiceTime, Date endInvoiceTime, String profile);

	List<Invoice> findAllByMaterialContainingAndInvoiceTimeGreaterThanEqualAndInvoiceTimeLessThanEqualAndDummyFalseAndProfileOrderByInvoiceNoAsc(String material, Date startInvoiceTime, Date endInvoiceTime, String profile);

	List<Invoice> findAllByInvoiceTimeGreaterThanEqualAndInvoiceTimeLessThanEqualAndDummyFalseAndProfileOrderByInvoiceNoAsc(Date startInvoiceTime, Date endInvoiceTime, String profile);


	Long deleteByProfile(String profile);

	Invoice findFirstByInvoiceNoAndProfileAndDummyTrue(int invoiceNo, String profile);

}
