INSERT INTO PROFILE
SELECT 'Standard', true
FROM DUAL
WHERE NOT EXISTS(SELECT * FROM PROFILE WHERE PROFILE_NAME like 'Standard');

INSERT INTO ADMIN_SETTINGS
SELECT 'REFRESH_TIME_WEIGHT', 250
FROM DUAL
WHERE NOT EXISTS(SELECT * FROM ADMIN_SETTINGS WHERE KEY = 'REFRESH_TIME_WEIGHT');
INSERT INTO ADMIN_SETTINGS
SELECT 'RESET_SLIP_PASSWORD', '123456'
FROM DUAL
WHERE NOT EXISTS(SELECT * FROM ADMIN_SETTINGS WHERE KEY = 'RESET_SLIP_PASSWORD');
INSERT INTO ADMIN_SETTINGS
SELECT 'MANUAL_ENTRY_PASSWORD', '123456'
FROM DUAL
WHERE NOT EXISTS(SELECT * FROM ADMIN_SETTINGS WHERE KEY = 'MANUAL_ENTRY_PASSWORD');
INSERT INTO ADMIN_SETTINGS
SELECT 'EDIT_ENABLE_PASSWORD', '123456'
FROM DUAL
WHERE NOT EXISTS(SELECT * FROM ADMIN_SETTINGS WHERE KEY = 'EDIT_ENABLE_PASSWORD');

INSERT INTO SETTINGS
SELECT 'Standard_slipNo', 'slipNo', 1, 'Standard'
FROM DUAL
WHERE NOT EXISTS(SELECT * FROM SETTINGS WHERE KEY = 'slipNo' AND PROFILE_PROFILE_NAME like 'Standard');
INSERT INTO SETTINGS
SELECT 'Standard_weighbridgeName', 'weighbridgeName', 'Babulens Enterprises', 'Standard'
FROM DUAL
WHERE NOT EXISTS(SELECT * FROM SETTINGS WHERE KEY = 'weighbridgeName' AND PROFILE_PROFILE_NAME like 'Standard');
INSERT INTO SETTINGS
SELECT 'Standard_weighbridgeAddress', 'weighbridgeAddress', 'Nagercoil', 'Standard'
FROM DUAL
WHERE NOT EXISTS(SELECT * FROM SETTINGS WHERE KEY = 'weighbridgeAddress' AND PROFILE_PROFILE_NAME like 'Standard');
INSERT INTO SETTINGS
SELECT 'Standard_footer', 'footer', '', 'Standard'
FROM DUAL
WHERE NOT EXISTS(SELECT * FROM SETTINGS WHERE KEY = 'footer' AND PROFILE_PROFILE_NAME like 'Standard');
INSERT INTO SETTINGS
SELECT 'Standard_printerName', 'printerName', 'get as .pdf File', 'Standard'
FROM DUAL
WHERE NOT EXISTS(SELECT * FROM SETTINGS WHERE KEY = 'printerName' AND PROFILE_PROFILE_NAME like 'Standard');
INSERT INTO SETTINGS
SELECT 'Standard_noOfCopies', 'noOfCopies', 1, 'Standard'
FROM DUAL
WHERE NOT EXISTS(SELECT * FROM SETTINGS WHERE KEY = 'noOfCopies' AND PROFILE_PROFILE_NAME like 'Standard');
INSERT INTO SETTINGS
SELECT 'Standard_printFormat', 'printFormat', 'WebCam Print', 'Standard'
FROM DUAL
WHERE NOT EXISTS(SELECT * FROM SETTINGS WHERE KEY = 'printFormat' AND PROFILE_PROFILE_NAME like 'Standard');

INSERT INTO COMM_PORT_SETTINGS
SELECT 'indicator',
       '1200',
       'Dummy',
       '8',
       '10',
       'Hardware',
       '~~~',
       'None',
       '1'
FROM DUAL
WHERE NOT EXISTS(SELECT * FROM COMM_PORT_SETTINGS WHERE NAME LIKE 'indicator' AND TYPE LIKE 'INDICATOR');

