INSERT INTO PROFILE
SELECT 'Standard', true
FROM DUAL
WHERE NOT EXISTS(SELECT * FROM PROFILE WHERE PROFILE_NAME like 'Standard');

INSERT INTO ADMIN_SETTING
SELECT 'REFRESH_TIME_WEIGHT', 250
FROM DUAL
WHERE NOT EXISTS(SELECT * FROM ADMIN_SETTING WHERE KEY = 'REFRESH_TIME_WEIGHT');
INSERT INTO ADMIN_SETTING
SELECT 'RESET_SLIP_PASSWORD', '123456'
FROM DUAL
WHERE NOT EXISTS(SELECT * FROM ADMIN_SETTING WHERE KEY = 'RESET_SLIP_PASSWORD');
INSERT INTO ADMIN_SETTING
SELECT 'MANUAL_ENTRY_PASSWORD', '123456'
FROM DUAL
WHERE NOT EXISTS(SELECT * FROM ADMIN_SETTING WHERE KEY = 'MANUAL_ENTRY_PASSWORD');
INSERT INTO ADMIN_SETTING
SELECT 'EDIT_ENABLE_PASSWORD', '123456'
FROM DUAL
WHERE NOT EXISTS(SELECT * FROM ADMIN_SETTING WHERE KEY = 'EDIT_ENABLE_PASSWORD');

INSERT INTO SETTING
SELECT 'Standard_slipNo', 'slipNo', 'Standard', 1
FROM DUAL
WHERE NOT EXISTS(SELECT * FROM SETTING WHERE KEY = 'slipNo' AND PROFILE like 'Standard');
INSERT INTO SETTING
SELECT 'Standard_weighbridgeName', 'weighbridgeName', 'Standard', 'Babulens Enterprises'
FROM DUAL
WHERE NOT EXISTS(SELECT * FROM SETTING WHERE KEY = 'weighbridgeName' AND PROFILE like 'Standard');
INSERT INTO SETTING
SELECT 'Standard_weighbridgeAddress', 'weighbridgeAddress', 'Standard', 'Nagercoil'
FROM DUAL
WHERE NOT EXISTS(SELECT * FROM SETTING WHERE KEY = 'weighbridgeAddress' AND PROFILE like 'Standard');
INSERT INTO SETTING
SELECT 'Standard_footer', 'footer', 'Standard', ''
FROM DUAL
WHERE NOT EXISTS(SELECT * FROM SETTING WHERE KEY = 'footer' AND PROFILE like 'Standard');
INSERT INTO SETTING
SELECT 'Standard_printerName', 'printerName', 'Standard', 'get as .pdf File'
FROM DUAL
WHERE NOT EXISTS(SELECT * FROM SETTING WHERE KEY = 'printerName' AND PROFILE like 'Standard');
INSERT INTO SETTING
SELECT 'Standard_noOfCopies', 'noOfCopies', 'Standard', 1
FROM DUAL
WHERE NOT EXISTS(SELECT * FROM SETTING WHERE KEY = 'noOfCopies' AND PROFILE like 'Standard');
INSERT INTO SETTING
SELECT 'Standard_printFormat', 'printFormat', 'Standard', 'WebCam Print'
FROM DUAL
WHERE NOT EXISTS(SELECT * FROM SETTING WHERE KEY = 'printFormat' AND PROFILE like 'Standard');
INSERT INTO SETTING
SELECT 'Standard_automation', 'automation', 'Standard', false
FROM DUAL
WHERE NOT EXISTS(SELECT * FROM SETTING WHERE KEY = 'automation' AND PROFILE like 'Standard');

INSERT INTO SERIAL_PORT_DETAIL
SELECT 'indicator',
       1200,
       8,
       10,
       0,
       '~~~',
       0,
       'dummy',
       1
FROM DUAL
WHERE NOT EXISTS(SELECT * FROM SERIAL_PORT_DETAIL WHERE NAME LIKE 'indicator');
INSERT INTO SERIAL_PORT_DETAIL
SELECT 'display',
       1200,
       8,
       10,
       0,
       '~~~',
       0,
       'dummy',
       1
FROM DUAL
WHERE NOT EXISTS(SELECT * FROM SERIAL_PORT_DETAIL WHERE NAME LIKE 'display');

INSERT INTO WEB_CAM_DETAIL
SELECT 'dummy', 5, true, 5, 0, 0
FROM DUAL
WHERE NOT EXISTS(SELECT * FROM WEB_CAM_DETAIL WHERE NAME LIKE 'dummy');